<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
#Importing libraries
import numpy as np


In [2]:
#Finding the version of NumPy
print(np.__version__)

1.15.4


In [3]:
#creating an array from a list
my_list = [-17, 0, 4, 5, 9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [4]:
#Multiplying each by 10
my_array_from_list * 10 

array([-170,    0,   40,   50,   90])

In [6]:
#Array from tuple
#This creates uniformity of numpy data structures
my_tuple = (14, -3.54, 5+7j)
my_array_from_tuple = np.array(my_tuple)
my_array_from_tuple

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between Python and NumPy data structures

In [7]:
my_tuple * 6 #Here * is a replicator

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [8]:
my_array_from_tuple * 6 # Here * is a multiplier

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])