<h1>Broadcasting</h1>

In [0]:
import numpy as np

In [2]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [0]:
#Broadcasting means operations on Arrays of different sizes. Smaller array 
#broadcasted on the bigger


In [3]:
#shape
my_3D_array.shape

(2, 7, 5)

In [4]:
#No. of dimensions
my_3D_array.ndim

3

In [5]:
#size
my_3D_array.size

70

In [6]:
#Datatype
my_3D_array.dtype

dtype('int64')

In [7]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [15]:
left_mat = np.arange(6).reshape(2,3)
right_mat = np.arange(15).reshape(3,5)
right_mat


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
np.inner(left_mat, right_mat)

ValueError: ignored

In [14]:
np.dot(left_mat,right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [17]:
### operations along the axes

my_3D_array.shape

(2, 7, 5)

In [18]:
my_3D_array.sum()

2415

In [22]:
69*70/2    ###(n-1)(n)/2

2415

In [23]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [24]:
my_3D_array.sum(axis = 0) #Summation of the matrices within a 3 D array along rows

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [25]:
my_3D_array.sum(axis = 1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [26]:
my_3D_array.sum(axis = 2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

# Broadcasting Rules

In [27]:
my_2D_array = np.ones(35, dtype = 'int_').reshape((7,5))*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [37]:
my_random_2D_array = np.random.rand(7,5)
my_random_2D_array

array([[0.70107556, 0.61336165, 0.34038897, 0.86652214, 0.35490437],
       [0.90329944, 0.78797728, 0.36619949, 0.95643221, 0.59772564],
       [0.2449488 , 0.0845616 , 0.71091028, 0.61991298, 0.97533725],
       [0.81413009, 0.2984894 , 0.31758338, 0.03408791, 0.23479697],
       [0.12490393, 0.0464648 , 0.02283882, 0.9085278 , 0.91543129],
       [0.1698503 , 0.64468805, 0.37168629, 0.11854799, 0.38479671],
       [0.21363861, 0.42615853, 0.25583289, 0.91557966, 0.58626176]])

In [38]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.6134,  0.6808,  2.5996,  1.4196],
        [ 4.5165,  4.7279,  2.5634,  7.6515,  5.3795],
        [ 2.4495,  0.9302,  8.5309,  8.0589, 13.6547],
        [12.212 ,  4.7758,  5.3989,  0.6136,  4.4611],
        [ 2.4981,  0.9758,  0.5025, 20.8961, 21.9704],
        [ 4.2463, 16.7619, 10.0355,  3.3193, 11.1591],
        [ 6.4092, 13.2109,  8.1867, 30.2141, 19.9329]],

       [[24.5376, 22.081 , 12.5944, 32.9278, 13.8413],
        [36.132 , 32.3071, 15.3804, 41.1266, 26.2999],
        [11.0227,  3.8898, 33.4128, 29.7558, 47.7915],
        [40.7065, 15.223 , 16.5143,  1.8067, 12.679 ],
        [ 6.8697,  2.602 ,  1.3018, 52.6946, 54.0104],
        [10.191 , 39.326 , 23.0445,  7.4685, 24.627 ],
        [13.8865, 28.1265, 17.1408, 62.2594, 40.4521]]])

In [39]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [42]:
np.set_printoptions(precision=4)
my_3D_array / my_vector

array([[[  0,   0,   0,   0,   0],
        [ -5,   0,   0,   0,   0],
        [-10,   1,   0,   0,   0],
        [-15,   2,   1,   0,   0],
        [-20,   3,   1,   1,   0],
        [-25,   3,   1,   1,   1],
        [-30,   4,   2,   1,   1]],

       [[-35,   5,   2,   1,   1],
        [-40,   5,   3,   2,   1],
        [-45,   6,   3,   2,   1],
        [-50,   7,   3,   2,   1],
        [-55,   8,   4,   2,   2],
        [-60,   8,   4,   3,   2],
        [-65,   9,   4,   3,   2]]])

In [43]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])