<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [5]:
#importing libraries
import numpy as np


In [6]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
a = np.arange(10,23, dtype = float)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

In [12]:
len(a)

13

In [14]:
my_range_array = np.arange(10,23, dtype = float)
my_range_array.size

13

In [15]:
a.size

13

In [17]:
#Excludes the stop value
b = np.arange(10,23,5,dtype = int)
b

array([10, 15, 20])

In [20]:
c = np.arange(26, step = 5)
print (c)

[ 0  5 10 15 20 25]
